import Item from "../components/Item";
import CreateItemForm from "../components/CreateItemForm";

export default function SingleList({ title, listId }) {
  return (
    <>
      <div className="px-4 sm:px-8 md:px-16 lg:px-20 xl:px-24 py-10 flex space-x-12">
        <div className="w-3/12">
          <h2 className="text-transparent text-xl">.</h2>
          <div className="border-b border-gray-300 my-4"></div>
          {/* START OF FORM */}
          <CreateItemForm />
        </div>
        <div className="w-9/12">
          <h2 className="text-xl font-medium">{title} Items</h2>
          <div className="border-b border-gray-300 my-4"></div>
          {/* ITEMS CONTAINER */}
          <div className="flex flex-wrap">
            <Item
              key="unique_item_key_1"
              itemName="Autogenerated Item 1"
              itemPrice={25.99}
              itemSize="M"
              itemUrl="autogen_item_url_1"
              itemId="autogen_item_id_1"
              listId={listId}
            />
            <Item
              key="unique_item_key_2"
              itemName="Autogenerated Item 2"
              itemPrice={19.99}
              itemSize="L"
              itemUrl="autogen_item_url_2"
              itemId="autogen_item_id_2"
              listId={listId}
            />
          </div>
        </div>
      </div>
    </>
  );
}
